

title: Task
email: viraj.chaudhary@apexure.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "https://virajchuaudhary.github.io/task/" # the subpath of your site, e.g. /blog
url: "https://virajchuaudhary.github.io/task/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  virajchuaudhary

# collections
collections:
  team: 
    title: Our team
    output: true
  clients:
    title: Our clients
    output: true   
  services:
    title: our services
    output: true  
plugins:
  - jekyll-paginate-v2


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2


exclude:
- Gemfile.lock
- node_modules/
pagination:
  enabled: true
  per_page: 6
  offset: 0
  permalink: "/page/:num/"
  title: ":title - page :num of :max"
  limit: 0
  sort_field: date
  sort_reverse: true

